### ISSUE TITLE
Error in App when I click on send steem 

### ISSUE THREAD

**Issue by Mistakili** [roelandp/steemwallet#35]
### Description
When I clicked on send, the app popped up an error message
### Expected behavior
I expected it to allow me create a paraphrase and add my private key to enable me send steem to another recipient.
### Steps to reproduce
Launch the app
Click on send below by the left side and note the error message.
### Devise used
HTC 
Android 6.0.1
App version. Current version

![iss](https://user-images.githubusercontent.com/50622055/59162326-c4c70800-8ae6-11e9-89ce-598105c68c0e.JPG)

**Comment by roelandp** [comment]
hi. it seems you are offline? 

can you go in your browser to api.coingecko.com ?

the error is unrelated to the send button as far as i can conclude from the error window. 

thank you for helping debugging this. 

roeland

**Comment by Mistakili** [comment]
Hi, I'm online now. 

I'm visiting the site...what should I do next?

*the error is unrelated to the send button as far as i can conclude from the error window.* >> it kept on popping up when I clicked send...and i had to shut it down and restart before I could do anything else. 

It happened like 4 times

**Comment by roelandp** [comment]
ok thanks I will see if i can reproduce it, and make the error more graceful. did you successfully submit your transfer now? 

thanks for your help. 

The coingecko api supplies the actual steem/sbd price in the currency you want to display it at. It tries to fetch prices once now and then. Most probably when it fails, it tries again instantly and gives the error. And again, and again, and again. I will see to fix this. 

thanks for the report. added to todo.

**Comment by Mistakili** [comment]
Awesome. Yes I could.
