### ISSUE TITLE
Dapp browser: Unable to serialize comment() transaction

### ISSUE THREAD

**Issue by tiotdev** [roelandp/steemwallet#37]
Using the comment() operation from steemconnect-js that works fine with Keychain on Desktop throws an exception with Steemwallet

![](https://res.cloudinary.com/dmuksl47x/image/upload/v1565733077/Screenshot_20190813-233114_godgen.jpg)

![](https://res.cloudinary.com/dmuksl47x/image/upload/v1565733069/Screenshot_20190813-233138_nvszri.jpg)

**Comment by roelandp** [comment]
Hi Julian, thx for your reply, 

can you link me up with a live sample so I can test & debug?

where are you experiencing this? 

thank you!

roeland

**Comment by tiotdev** [comment]
Sorry, forgot to add it: https://travelfeed.io/

**Comment by roelandp** [comment]
thanks for your report. I noticed this is also not working on SteemPeak, something with parent_username / parent_author . let's see how to fix. 

thanks!
